version: "3.8"

services:
  nextap:
    image: ghcr.io/ocinz/nihongo-gakkou:latest
  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env
    # environment:
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
