services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nextap:
    container_name: nihongo
    image: nihongo
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env

    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - postgres

volumes:
  postgres-data: {}
