version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    env_file: ".env"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  nextap:
    image: ghcr.io/ocinz/nihongo-gakkou:${BUILD_NUMBER}
    container_name: nihongo
    working_dir: /app
    env_file: ".env"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
    ports:
      - "3001:3000"
    depends_on:
      - postgres

volumes:
  postgres-data:
