version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  nextap:
    image: ghcr.io/ocinz/nihongo-gakkou:latest
    container_name: nihongo
    working_dir: /app
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/mydatabase
    command: sh -c "npm install && npm run dev"
    depends_on:
      - postgres

volumes:
  postgres-data:
