services:
  postgres:
    image: postgres:15
    container_name: postgres
    # restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nextjs:
    container_name: nihongo
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
    ports:
      - 3001:3001
    depends_on:
      - postgres
    # environment:
    #   DATABASE_URL: ${DATABASE_URL}
    volumes: []

volumes:
  postgres-data: {}
