services:
  postgres:
    image: postgres:15
    container_name: postgres
    # restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nextjs:
    container_name: nihongo
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        AUTH_GOOGLE_ID: ${AUTH_GOOGLE_ID}
        AUTH_GOOGLE_SECRET: ${AUTH_GOOGLE_SECRET}
        NODE_ENV: ${NODE_ENV}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        AUTH_TRUST_HOST: ${AUTH_TRUST_HOST}
        PORT: ${PORT}
        DATABASE_URL: ${DATABASE_URL}
    environment:
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
      - NODE_ENV=${NODE_ENV}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - AUTH_TRUST_HOST=${AUTH_TRUST_HOST}
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 3001:3001
    depends_on:
      - postgres

volumes:
  postgres-data: {}
